import { Router } from 'express';

import adminAdminsRouter from './admin/admins/route.js';
import adminChangePasswordRouter from './admin/auth/change-password/route.js';
import adminForgotPasswordRouter from './admin/auth/forgot-password/route.js';
import adminLoginRouter from './admin/auth/login/route.js';
import adminLogoutRouter from './admin/auth/logout/route.js';
import adminRegisterRouter from './admin/auth/register/route.js';
import adminResetPasswordRouter from './admin/auth/reset-password/route.js';
import adminDashboardRouter from './admin/dashboard/route.js';
import adminProfileRouter from './admin/profile/route.js';
import adminReportsRouter from './admin/reports/route.js';
import adminSettingsRouter from './admin/settings/route.js';
import adminTraderDetailsRouter from './admin/traders/[id]/route.js';
import adminTradersRouter from './admin/traders/route.js';
import adminVerifyTraderRouter from './admin/traders/verify/route.js';
import publicSettingsRouter from './settings/public/route.js';
import userForgotPasswordRouter from './user/auth/forgot-password/route.js';
import userLoginRouter from './user/auth/login/route.js';
import userLogoutRouter from './user/auth/logout/route.js';
import userRegisterRouter from './user/auth/register/route.js';
import userResetPasswordRouter from './user/auth/reset-password/route.js';
import userVerifyOtpRouter from './user/auth/verify-otp/route.js';
import customerDetailsRouter from './user/customers/[id]/route.js';
import customersRouter from './user/customers/route.js';
import userDashboardRouter from './user/dashboard/route.js';
import productDetailsRouter from './user/products/[id]/route.js';
import productsRouter from './user/products/route.js';
import userProfileRouter from './user/profile/route.js';
import providerDetailsRouter from './user/providers/[id]/route.js';
import providersRouter from './user/providers/route.js';
import purchaseDetailsRouter from './user/purchases/[id]/route.js';
import purchasesRouter from './user/purchases/route.js';
import userReportsRouter from './user/reports/route.js';
import saleDetailsRouter from './user/sales/[id]/route.js';
import salesRouter from './user/sales/route.js';
import userSettingsRouter from './user/settings/route.js';
import userVerificationRouter from './user/verify-trader/route.js';

const apiRouter = Router();

apiRouter.use('/admin/admins', adminAdminsRouter);
apiRouter.use('/admin/auth/change-password', adminChangePasswordRouter);
apiRouter.use('/admin/auth/forgot-password', adminForgotPasswordRouter);
apiRouter.use('/admin/auth/login', adminLoginRouter);
apiRouter.use('/admin/auth/logout', adminLogoutRouter);
apiRouter.use('/admin/auth/register', adminRegisterRouter);
apiRouter.use('/admin/auth/reset-password', adminResetPasswordRouter);
apiRouter.use('/admin/dashboard', adminDashboardRouter);
apiRouter.use('/admin/profile', adminProfileRouter);
apiRouter.use('/admin/reports', adminReportsRouter);
apiRouter.use('/admin/settings', adminSettingsRouter);
apiRouter.use('/admin/traders/verify', adminVerifyTraderRouter);
apiRouter.use('/admin/traders/:id', adminTraderDetailsRouter);
apiRouter.use('/admin/traders', adminTradersRouter);
apiRouter.use('/settings/public', publicSettingsRouter);
apiRouter.use('/user/auth/forgot-password', userForgotPasswordRouter);
apiRouter.use('/user/auth/login', userLoginRouter);
apiRouter.use('/user/auth/logout', userLogoutRouter);
apiRouter.use('/user/auth/register', userRegisterRouter);
apiRouter.use('/user/auth/reset-password', userResetPasswordRouter);
apiRouter.use('/user/auth/verify-otp', userVerifyOtpRouter);
apiRouter.use('/user/customers/:id', customerDetailsRouter);
apiRouter.use('/user/customers', customersRouter);
apiRouter.use('/user/dashboard', userDashboardRouter);
apiRouter.use('/user/products/:id', productDetailsRouter);
apiRouter.use('/user/products', productsRouter);
apiRouter.use('/user/profile', userProfileRouter);
apiRouter.use('/user/providers/:id', providerDetailsRouter);
apiRouter.use('/user/providers', providersRouter);
apiRouter.use('/user/purchases/:id', purchaseDetailsRouter);
apiRouter.use('/user/purchases', purchasesRouter);
apiRouter.use('/user/reports', userReportsRouter);
apiRouter.use('/user/sales/:id', saleDetailsRouter);
apiRouter.use('/user/sales', salesRouter);
apiRouter.use('/user/settings', userSettingsRouter);
apiRouter.use('/user/verify-trader', userVerificationRouter);

export default apiRouter;
